// Regenerates lib/data/troopIconTemplates.ts from the ORIGINAL package roster
// screenshots (01_roster). Run: npx tsx scripts/buildTroopIconTemplates.ts
// The 06_real_test_cases screenshots are deliberately NOT used, so they stay
// an independent test set.
import fs from "fs";
import path from "path";
import { decodeImageFile } from "../__tests__/helpers/decodeImage";
import { segmentRosterCards } from "../imageRecognition/rosterSegmenter";
import { crop } from "../imageRecognition/pixels";
import { buildTroopIconTemplates } from "../imageRecognition/cardSignals";
import { getHeroDefinition } from "../lib/data/heroDatabase";

const ROOT = path.join(__dirname, "..");
const TRUTH: Record<string, string[]> = {
  "hero_roster_power_page_1.jpeg": ["mia", "flint", "molly", "alonso", "gina", "jessie", "patrick", "lynn", "jeronimo", "sergey", "bahiti", "cloris", "eugene", "zinman", "charlie", "reina"],
  "hero_roster_power_page_2.jpeg": ["smith", "philly", "lumak-bokan", "natalia", "jasser", "greg", "seo-yoon", "ling-xue", "ahmose", "logan"],
};
const samples = Object.entries(TRUTH).flatMap(([file, ids]) => {
  const img = decodeImageFile(path.join(ROOT, "docs/package/reference-screenshots/01_roster", file));
  return segmentRosterCards(img).cards.map((b, i) => ({ card: crop(img, b), troopType: getHeroDefinition(ids[i])!.troopType }));
});
const t = buildTroopIconTemplates(samples);
fs.writeFileSync(
  path.join(ROOT, "lib/data/troopIconTemplates.ts"),
  `// GENERATED by scripts/buildTroopIconTemplates.ts from docs/package/reference-screenshots/01_roster
// (${samples.length} cards of known heroes). 20x20 zero-mean unit-norm "whiteness" maps of the troop icon.
import { TroopType } from "../types";
export const TROOP_ICON_TEMPLATES: Record<TroopType, number[]> = ${JSON.stringify(t)};
`
);
console.log("templates from", samples.length, "cards:", Object.keys(t).map((k) => `${k}`).join(", "));
